# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mywant < Formula
  desc "Declarative chain programming system - express what you want via YAML, autonomous agents execute it"
  homepage "https://github.com/onelittlenightmusic/MyWant"
  version "0.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.14.0/mywant_0.14.0_darwin_amd64.tar.gz"
      sha256 "4d8189fa1922d4b3e67762079a500b001976deb27e8a1431440c3aa46569303d"

      define_method(:install) do
        bin.install "mywant"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.14.0/mywant_0.14.0_darwin_arm64.tar.gz"
      sha256 "af69cf98b916c7b1512e699271f495069e670409a9aae36e8523106683eb4972"

      define_method(:install) do
        bin.install "mywant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.14.0/mywant_0.14.0_linux_amd64.tar.gz"
      sha256 "81518b866f5ee87907782e5284646c676848f1476fc21e9ed5c25e18fecd6d9d"
      define_method(:install) do
        bin.install "mywant"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.14.0/mywant_0.14.0_linux_arm64.tar.gz"
      sha256 "1fef757bbcafad53701a391e34a1c255edab35be28ad73a47a2ad72bf0a17e45"
      define_method(:install) do
        bin.install "mywant"
      end
    end
  end

  service do
    run [opt_bin/"mywant", "start"]
    keep_alive true
    log_path var/"log/mywant.log"
    error_log_path var/"log/mywant.log"
  end

  test do
    system "#{bin}/mywant", "--version"
  end
end
