# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MywantRpg < Formula
  desc "MyWant RPG plugin - CLI interface to the skills-rpg game server"
  homepage "https://github.com/onelittlenightmusic/skills-rpg"
  version "0.1.21"
  license "MIT"

  depends_on "mywant"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v0.1.21/mywant-rpg_0.1.21_darwin_amd64.tar.gz"
      sha256 "c3476c03af1ef2852c5a234dac733e7186bb30a83d40afd8563dddd8051538ad"

      define_method(:install) do
        bin.install "mywant-rpg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v0.1.21/mywant-rpg_0.1.21_darwin_arm64.tar.gz"
      sha256 "386e33fa17a69a86f6cfac78b3ed2f3160829b66d3bcef042e358b1679029646"

      define_method(:install) do
        bin.install "mywant-rpg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v0.1.21/mywant-rpg_0.1.21_linux_amd64.tar.gz"
      sha256 "96831180147b58a837d9e5cf3f72cf26d048d53bed1fea8d99d5dbd7445bbfb6"
      define_method(:install) do
        bin.install "mywant-rpg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v0.1.21/mywant-rpg_0.1.21_linux_arm64.tar.gz"
      sha256 "aa42cd5710078242384310afb755a97845fd541b9d5161a7fd3fccaddcb3f8d5"
      define_method(:install) do
        bin.install "mywant-rpg"
      end
    end
  end

  test do
    system "#{bin}/mywant-rpg", "--version"
  end
end
