# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MywantGuiex < Formula
  desc "The MyWant canvas — board, kata, characters and the robot — as an extension of mywant-gui, and its CLI (mywant guiex)"
  homepage "https://github.com/onelittlenightmusic/mywant-gui-dist"
  version "0.6.164"
  license "MIT"

  depends_on "mywant"
  depends_on "mywant-gui"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.164/mywant-guiex_0.6.164_darwin_amd64.tar.gz"
      sha256 "fd77ea2da2d539b1ace3b664b4a07ab6786a4adf8f3dcfec78c4484cd10a7337"

      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.164/mywant-guiex_0.6.164_darwin_arm64.tar.gz"
      sha256 "892b19188babfdd5d9cd417985e2ab35198de22ff3906c78b35af0623ec29672"

      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.164/mywant-guiex_0.6.164_linux_amd64.tar.gz"
      sha256 "0ff861a7feb1898a8849dfbe0a053accb6afff91c61f5c24c18948891b40b24a"
      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.164/mywant-guiex_0.6.164_linux_arm64.tar.gz"
      sha256 "01365182d5d28f9666ca3a9e42f905b944f9728026b10a8494323b684dab21b7"
      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
  end

  def caveats
    <<~EOS
      The canvas is an extension of mywant-gui, installed with this formula.
      Start the GUI as usual (`mywant gui start -D` or
      `brew services start mywant-gui`) and reload the page.

      It is built for the mywant-gui of the same version: upgrade the two
      together (`brew upgrade mywant-gui mywant-guiex`).
    EOS
  end

  test do
    system "#{bin}/mywant-guiex", "--help"
  end
end
