# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MywantGui < Formula
  desc "MyWant GUI server — serves the web frontend and proxies API requests to the MyWant backend"
  homepage "https://github.com/onelittlenightmusic/mywant-gui"
  version "0.6.16"
  license "MIT"

  depends_on "mywant"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.16/mywant-gui_0.6.16_darwin_amd64.tar.gz"
      sha256 "9da6a7a17b2b78f5516392d804fa03256331e6d369d79e749af73f0dbf9192a1"

      define_method(:install) do
        bin.install "mywant-gui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.16/mywant-gui_0.6.16_darwin_arm64.tar.gz"
      sha256 "636d2792318e2911b9f813e9f6745db551de3ef0556d94a3a75caefd23023531"

      define_method(:install) do
        bin.install "mywant-gui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.16/mywant-gui_0.6.16_linux_amd64.tar.gz"
      sha256 "6deaf4eb5de04f9507c65d92c91fa9020559705f3ddb354ad61a9aad85aa7e81"
      define_method(:install) do
        bin.install "mywant-gui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.16/mywant-gui_0.6.16_linux_arm64.tar.gz"
      sha256 "1f8a7ea8712c7292223e6698fff23f911fdc74453bf49b016cd927d7d7d275e8"
      define_method(:install) do
        bin.install "mywant-gui"
      end
    end
  end

  service do
    run [opt_bin/"mywant-gui", "start"]
    keep_alive true
    log_path var/"log/mywant-gui.log"
    error_log_path var/"log/mywant-gui.log"
  end

  test do
    system "#{bin}/mywant-gui", "--help"
  end
end
