# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mywant < Formula
  desc "Declarative chain programming system - express what you want via YAML, autonomous agents execute it"
  homepage "https://github.com/onelittlenightmusic/MyWant"
  version "0.17.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.17.19/mywant_0.17.19_darwin_amd64.tar.gz"
      sha256 "5cad3d7169903c6005548938470e09a3375209ff5fabd3eab8611b0140b9425a"

      define_method(:install) do
        bin.install "mywant"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.17.19/mywant_0.17.19_darwin_arm64.tar.gz"
      sha256 "1baf3b343687ad575610a514b30a748d3ea4f7d9d4291f925aca529a1f01f66b"

      define_method(:install) do
        bin.install "mywant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.17.19/mywant_0.17.19_linux_amd64.tar.gz"
      sha256 "124a3f48d413046191b5e0960e173bf0a76ce57275e8ab21e922285e16147961"
      define_method(:install) do
        bin.install "mywant"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.17.19/mywant_0.17.19_linux_arm64.tar.gz"
      sha256 "fc43867f7df3a55aee245408c6b60809e2e7ae6e138ab90d555ac3c12cc591e3"
      define_method(:install) do
        bin.install "mywant"
      end
    end
  end

  service do
    run [opt_bin/"mywant", "start"]
    keep_alive true
    log_path var/"log/mywant.log"
    error_log_path var/"log/mywant.log"
  end

  test do
    system "#{bin}/mywant", "--version"
  end
end
