# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MywantGuiex < Formula
  desc "The MyWant canvas — board, kata, characters and the robot — as an extension of mywant-gui, and its CLI (mywant guiex)"
  homepage "https://github.com/onelittlenightmusic/mywant-gui-dist"
  version "0.6.175"
  license "MIT"

  depends_on "mywant"
  depends_on "mywant-gui"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.175/mywant-guiex_0.6.175_darwin_amd64.tar.gz"
      sha256 "24e528072b9b2e2eaca393f4cd65f1d60579ea887988becb5f66a97ca105f407"

      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.175/mywant-guiex_0.6.175_darwin_arm64.tar.gz"
      sha256 "3e5f5e0b914bf3b49d4cd48c005b123a2c85f7cf8305a9e6b48897d8a4e10b04"

      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.175/mywant-guiex_0.6.175_linux_amd64.tar.gz"
      sha256 "c711817aa9d9d12117e66afa244c6d77356bc6e96875e84db121976cd77538e0"
      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.175/mywant-guiex_0.6.175_linux_arm64.tar.gz"
      sha256 "712ae31bd40cd316f2eed6584f959a4f204d176d7f84c2d8df246c541a6eb50d"
      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
  end

  def caveats
    <<~EOS
      The canvas is an extension of mywant-gui, installed with this formula.
      Start the GUI as usual (`mywant gui start -D` or
      `brew services start mywant-gui`) and reload the page.

      It is built for the mywant-gui of the same version: upgrade the two
      together (`brew upgrade mywant-gui mywant-guiex`).
    EOS
  end

  test do
    system "#{bin}/mywant-guiex", "--help"
  end
end
