# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MywantGuiex < Formula
  desc "The MyWant canvas — board, kata, characters and the robot — as an extension of mywant-gui, and its CLI (mywant guiex)"
  homepage "https://github.com/onelittlenightmusic/mywant-gui-dist"
  version "0.6.134"
  license "MIT"

  depends_on "mywant"
  depends_on "mywant-gui"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.134/mywant-guiex_0.6.134_darwin_amd64.tar.gz"
      sha256 "75ac60f0a8b4e8147c9ad3f1e6d15b77740d203373233deaad7bee1753283318"

      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.134/mywant-guiex_0.6.134_darwin_arm64.tar.gz"
      sha256 "ead514a095a2a5aebb8e761d5ea98babfdc96ba4d70514e2f8aff22a7a4eb550"

      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.134/mywant-guiex_0.6.134_linux_amd64.tar.gz"
      sha256 "23067a0efdca175b051d54319d8a23ac53428947258894405d40a8c8c64db77b"
      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.6.134/mywant-guiex_0.6.134_linux_arm64.tar.gz"
      sha256 "30637d3d45d346634a6bb94e430c1a57de9ddde305970b1872554a09bdaece81"
      define_method(:install) do
        bin.install "mywant-guiex"
        # The canvas, where mywant-gui looks for extensions under Homebrew's
        # prefix (share/ is linked into it). ~/.mywant/gui-extensions, written by
        # `mywant guiex install`, takes precedence over this copy.
        system bin/"mywant-guiex", "install", "--dir", share/"mywant/gui-extensions"
      end
    end
  end

  def caveats
    <<~EOS
      The canvas is an extension of mywant-gui, installed with this formula.
      Start the GUI as usual (`mywant gui start -D` or
      `brew services start mywant-gui`) and reload the page.

      It is built for the mywant-gui of the same version: upgrade the two
      together (`brew upgrade mywant-gui mywant-guiex`).
    EOS
  end

  test do
    system "#{bin}/mywant-guiex", "--help"
  end
end
