# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MywantGui < Formula
  desc "MyWant GUI server — serves the web frontend and proxies API requests to the MyWant backend"
  homepage "https://github.com/onelittlenightmusic/mywant-gui"
  version "0.3.77"
  license "MIT"

  depends_on "mywant"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.3.77/mywant-gui_0.3.77_darwin_amd64.tar.gz"
      sha256 "3e2da314420e3f3534edbdabbb37458559a0ad3aa2f5f19c6e5069459e09ed0f"

      define_method(:install) do
        bin.install "mywant-gui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.3.77/mywant-gui_0.3.77_darwin_arm64.tar.gz"
      sha256 "cc23279e59cce595146af4310096f5c0eddb2136d3437deae2fc04736504e0b2"

      define_method(:install) do
        bin.install "mywant-gui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.3.77/mywant-gui_0.3.77_linux_amd64.tar.gz"
      sha256 "069b3c02b3368ddf72a535e172279d1da0a07be836da739c9feb0812dea8f3ea"
      define_method(:install) do
        bin.install "mywant-gui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/mywant-gui-dist/releases/download/v0.3.77/mywant-gui_0.3.77_linux_arm64.tar.gz"
      sha256 "febcc86ab6e6d05272d11a49ed4c56439190a6310dc99f7567345fd2201dde19"
      define_method(:install) do
        bin.install "mywant-gui"
      end
    end
  end

  test do
    system "#{bin}/mywant-gui", "--help"
  end
end
