# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mywant < Formula
  desc "Declarative chain programming system - express what you want via YAML, autonomous agents execute it"
  homepage "https://github.com/onelittlenightmusic/MyWant"
  version "0.0.41"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.0.41/mywant_0.0.41_darwin_amd64.tar.gz"
      sha256 "9e2091d503c2a31fad8bdeee83c6f29749a5f060b4ceb7a74fb1a5db8a086f13"

      define_method(:install) do
        bin.install "mywant"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.0.41/mywant_0.0.41_darwin_arm64.tar.gz"
      sha256 "59c49d5a99ed232d87ead248637a21572986c68595a00a6cfb54d8d9d5d9545a"

      define_method(:install) do
        bin.install "mywant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.0.41/mywant_0.0.41_linux_amd64.tar.gz"
      sha256 "1c35d388d5c1dbf4f9744a734df243329b965566bb9eb5b9a217d351a9c0a981"
      define_method(:install) do
        bin.install "mywant"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v0.0.41/mywant_0.0.41_linux_arm64.tar.gz"
      sha256 "5b5a96d2acc5a849368e8bec20723851e81fb172acd57b8b27e4566c9070c329"
      define_method(:install) do
        bin.install "mywant"
      end
    end
  end

  test do
    system "#{bin}/mywant", "--version"
  end
end
