# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MywantRpg < Formula
  desc "MyWant RPG plugin - CLI interface to the skills-rpg game server"
  homepage "https://github.com/onelittlenightmusic/skills-rpg"
  version "0.0.1"
  license "MIT"

  depends_on "mywant"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v0.0.1/mywant-rpg_0.0.1_darwin_amd64.tar.gz"
      sha256 "199596e4c4ea963a8d5259b229c4f522d0ef5b51e8fc09c8fed10fb12d745fd4"

      define_method(:install) do
        bin.install "mywant-rpg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v0.0.1/mywant-rpg_0.0.1_darwin_arm64.tar.gz"
      sha256 "836a76f9d1362409a7543eb3b96b20cd5f71cde1d6bc5b379525edbf2cbd5c47"

      define_method(:install) do
        bin.install "mywant-rpg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v0.0.1/mywant-rpg_0.0.1_linux_amd64.tar.gz"
      sha256 "7f72dbacce616a3ea9ec9803514e912646d26a1b27c4a814f8a664e8c0f81a07"
      define_method(:install) do
        bin.install "mywant-rpg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v0.0.1/mywant-rpg_0.0.1_linux_arm64.tar.gz"
      sha256 "e94448415f0593607df65bb393708a6b5f231d66d2d982aea07d18b398cf9c9c"
      define_method(:install) do
        bin.install "mywant-rpg"
      end
    end
  end

  test do
    system "#{bin}/mywant-rpg", "--version"
  end
end
