# This file was generated by GoReleaser. DO NOT EDIT.
cask "mywant-rpg" do
  version "0.1.22"

  on_macos do
    on_intel do
      sha256 "a155e8b4be4ce6908c93b22ed16f8d5f792f9d8867e2fc1a36c43710b9032911"
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v#{version}/mywant-rpg_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4450c34125c1f616513840663d395634a723e61e946c49bcd516b166b1b60c8"
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v#{version}/mywant-rpg_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1e6f7a49f7f296ed6aa776d65e69f3bf4dea735099bd81158a8e28480ebb9ea5"
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v#{version}/mywant-rpg_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9d8dd3ddd2284c69c570ba79905449b3b01c085d3f665d3ba84db176fec6565b"
      url "https://github.com/onelittlenightmusic/skills-rpg/releases/download/v#{version}/mywant-rpg_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mywant-rpg"
  desc "MyWant RPG plugin - CLI interface to the skills-rpg game server"
  homepage "https://github.com/onelittlenightmusic/skills-rpg"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mywant",
    ]

  binary "mywant-rpg"

  # No zap stanza required

end
