# This file was generated by GoReleaser. DO NOT EDIT.
cask "mywant" do
  version "0.0.34"

  on_macos do
    on_intel do
      sha256 "0713ec10174a5b47d05ddc15194c0f24f74ec1b6da09808456b43589398ab22b"
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v#{version}/mywant_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d43518931d57e6b2a1ac960bb5282fca60b0390d5cf6784215f1bcec4a134286"
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v#{version}/mywant_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4edb31a929decec7b5943f407b4a4f3237306dbcd432e38ee5cbd08e6ca38f7"
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v#{version}/mywant_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fbbfc5c0ac9659c2e08f25fe5045215349d11e0404bbe4fabcfa49bf593eca02"
      url "https://github.com/onelittlenightmusic/MyWant/releases/download/v#{version}/mywant_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mywant"
  desc "Declarative chain programming system - express what you want via YAML, autonomous agents execute it"
  homepage "https://github.com/onelittlenightmusic/MyWant"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mywant"

  # No zap stanza required

end
